// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/gogf/gf-demos/app/model/internal"
)

// Match is the golang structure for table match.
type Match internal.Match

// Fill with you ideas below.