// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf-demos/app/model/internal"
)

// Rule is the golang structure for table rule.
type Rule internal.Rule

// Fill with you ideas below.