// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf-demos/app/model/internal"
)

// Score is the golang structure for table score.
type Score internal.Score

// Fill with you ideas below.