// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf-demos/app/model/internal"
)

// Subject is the golang structure for table subject.
type Subject internal.Subject

// Fill with you ideas below.