// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gmeta"
)

// Contestant is the golang structure for table contestant.
type Contestant struct {
	gmeta.Meta `orm:"table:contestant"`
	Id         int         `orm:"id,primary" json:"id"`        //
	Gid        int         `orm:"gid"        json:"gid"`       //
	Name       string      `orm:"name"       json:"name"`      //
	Region     string      `orm:"region"     json:"region"`    //
	Group      string      `orm:"group"      json:"group"`     //
	Province   string      `orm:"province"   json:"province"`  //
	CreatedAt  *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt  *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	UserScores []*Score    `orm:"with:contestant_id=id"`
}
