// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Match is the golang structure for table match.
type Match struct {
    Id        int         `orm:"id,primary" json:"id"`        //               
    Kvurl     string      `orm:"kvurl"      json:"kvurl"`     //               
    Title     string      `orm:"title"      json:"title"`     //               
    Index     string      `orm:"index"      json:"index"`     //               
    Type      int         `orm:"type"       json:"type"`      // 1:场内2:场外  
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //               
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //               
}