// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Rule is the golang structure for table rule.
type Rule struct {
    Id        int         `orm:"id,primary" json:"id"`        //   
    Title     string      `orm:"title"      json:"title"`     //   
    Rules     string      `orm:"rules"      json:"rules"`     //   
    Desc      string      `orm:"desc"       json:"desc"`      //   
    Imgurl    string      `orm:"imgurl"     json:"imgurl"`    //   
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //   
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //   
}