// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Rule is the golang structure for table rule.
type Rule struct {
    Id        int         `orm:"id,primary" json:"id"`        //             
    Title     string      `orm:"title"      json:"title"`     //             
    Score     int         `orm:"score"      json:"score"`     //             
    SubjectId int         `orm:"subject_id" json:"subjectId"` // subject id  
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //             
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //             
}