// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Score is the golang structure for table score.
type Score struct {
    Uid       int         `orm:"uid,primary" json:"uid"`       //   
    Cid       int         `orm:"cid"         json:"cid"`       //   
    Rules     string      `orm:"rules"       json:"rules"`     //   
    Score     float64     `orm:"score"       json:"score"`     //   
    Comments  string      `orm:"comments"    json:"comments"`  //   
    CreatedAt *gtime.Time `orm:"created_at"  json:"createdAt"` //   
    UpdatedAt *gtime.Time `orm:"updated_at"  json:"updatedAt"` //   
}