// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gmeta"
)

// Score is the golang structure for table score.
type Score struct {
	gmeta.Meta   `orm:"table:score"`
	Id           int         `orm:"id,primary"    json:"id"`           //
	ContestantId int         `orm:"contestant_id" json:"contestantId"` //
	SubjectId    int         `orm:"subject_id"    json:"subjectId"`    //
	UserId       int         `orm:"user_id"       json:"userId"`       //
	Vurl         string      `orm:"vurl"          json:"vurl"`         //
	Result       string      `orm:"result"        json:"result"`       //
	Score        float64     `orm:"score"         json:"score"`        //
	Comments     string      `orm:"comments"      json:"comments"`     //
	CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //
	UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //
}
