// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Subject is the golang structure for table subject.
type Subject struct {
    Id        int         `orm:"id,primary" json:"id"`        //   
    Name      string      `orm:"name"       json:"name"`      //   
    MatchId   int         `orm:"match_id"   json:"matchId"`   //   
    Img       string      `orm:"img"        json:"img"`       //   
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //   
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //   
}