// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
    Id        int         `orm:"id,primary" json:"id"`        //               
    Name      string      `orm:"name"       json:"name"`      //               
    Password  string      `orm:"password"   json:"password"`  //               
    Desc      string      `orm:"desc"       json:"desc"`      //               
    Tid       int         `orm:"tid"        json:"tid"`       //               
    Type      int         `orm:"type"       json:"type"`      // 1:场内2:场外  
    Starttime *gtime.Time `orm:"starttime"  json:"starttime"` //               
    Endtime   *gtime.Time `orm:"endtime"    json:"endtime"`   //               
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //               
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //               
}