# HTTP Server.
[server]
	address        = ":8080"
	serverRoot     = "public"
	serverAgent    = "skillscore"
	logPath        = "/tmp/log/skillscore/server"
	nameToUriType  = 2
	routeOverWrite = true

# Logger configurations.
[logger]
    path   = "/tmp/log/skillscore"
    level  = "all"
    stdout = true

# Template view configurations.
[viewer]
    path        = "template"
    defaultFile = "index.html"

# Database configurations.
[database]
    link   = "mysql:root:Oclzco6rQBD6i!4h@tcp(47.96.214.6:3306)/skillscore"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/skillscore/sql"
        Level  = "all"
        Stdout = true

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:root:Oclzco6rQBD6i!4h@tcp(47.96.214.6:3306)/skillscore"
        tables = "user,rule,contestant,match,score"

