// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demos/app/dao/internal"
)

// matchDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type matchDao struct {
	internal.MatchDao
}

var (
	// Match is globally public accessible object for table match operations.
	Match = matchDao{
		internal.Match,
	}
)

// Fill with you ideas below.