// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/gogf/gf-demos/app/model/internal"
)

// Contestant is the golang structure for table contestant.
type Contestant internal.Contestant

// Fill with you ideas below.